---

- name: Create forgejo secret key
  become: true
  containers.podman.podman_secret:
    state: present
    name: forgejo-secret-key
    data: "{{ fg_forgejo_secret_key }}"

- name: Create forgejo internal token
  become: true
  containers.podman.podman_secret:
    state: present
    name: forgejo-token-internal
    data: "{{ fg_forgejo_internal_token }}"

- name: Create forgejo jwt secret (oauth)
  become: true
  containers.podman.podman_secret:
    state: present
    name: forgejo-jwt-oauth
    data: "{{ fg_forgejo_jwt_oauth }}"

- name: Create forgejo jwt secret (lfs)
  become: true
  containers.podman.podman_secret:
    state: present
    name: forgejo-jwt-lfs
    data: "{{ fg_forgejo_jwt_lfs }}"
