---
# handlers file for fg_forgejo

- name: "Restart forgejo"
  become: true
  ansible.builtin.service:
    name: forgejo
    state: restarted

- name: "Reload systemd units"
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

